[theme]
base = "light"
primaryColor = "#F97316"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F4F6"
textColor = "#111827"
font = "sans serif"

[server]
runOnSave = true

[client]
showSidebarNavigation = false

[layout]
initialSidebarState = "expanded"

[browser]
gatherUsageStats = false
